spring.application.name=user-service

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/twitch_clone_user}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.initialization-mode=always

jwt.secret=mySecretKeyForJWTTokenGeneration123456789
jwt.expiration=86400000

logging.level.com.twitch.clone=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.orm.jpa=TRACE
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.crypto.bcrypt=DEBUG
